server {
    listen 80;
    root /usr/share/nginx/html;
    index widget.js;

    location / {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=3600";
        try_files $uri =404;
    }
}
